### ISSUE TITLE
getWorkStatus TypeError

### ISSUE THREAD

**Issue by Feeeeeelix** [ch3rn1k/homebridge-multipurpose-kettle#12]
[Multipurpose Kettle] getWorkStatus TypeError: callback is not a function
    at MiMultipurposeKettle.getWorkStatus (/usr/lib/node_modules/homebridge-multipurpose-kettle/index.js:102:7)

[homebridge-multipurpose-kettle] This plugin threw an error from the characteristic 'Current Heating Cooling State': Unhandled error thrown inside read handler for characteristic: callback is not a function. See https://git.io/JtMGR for more info.

**Comment by ch3rn1k** [comment]
Whoops, my fail. Going to fix now!

**Comment by ch3rn1k** [comment]
Reverted my changes, please update to `v 2.3.4.

Hope I will find some time to fix Homebridge errors
