### ISSUE TITLE
[Enhancement] "heat"

### ISSUE THREAD

**Issue by DJay-X** [ch3rn1k/homebridge-multipurpose-kettle#2]
@ch3rn1k First of all thanks for your great work, the time you are investing and sharing with the community. 🙏

Your Plugin was the reason I instantly bought the Xiaomi Multipurpose Kettle.
Unfortunately I have to wait a few weeks until it will arrive from CN.

Is your plugin able to use it for different heat temperatures?
Like asking Siri "turn the kettle to 100", "turn the kettle to 65"?
And of course an always default temp when turning on.
Can I already place some values in the config at once or do you see another idea?

Anyways, thanks again for this great plugin and your ongoing development. 
Can't wait to use it daily.

**Comment by ch3rn1k** [comment]
Thanks for your interest!

Right now it only works with commands "Turn ON/OFF", but I will dive into HEAT param for Siri commands, maybe I have an idea.

![image](https://user-images.githubusercontent.com/19375789/78988028-6d475d80-7b38-11ea-8e50-897763440980.png)

**Comment by ch3rn1k** [comment]
Added in the latest update `v2.0`. Use mode `Thermostat`, enjoy!
