### ISSUE TITLE
support for Xiaomi induction cooker?

### ISSUE THREAD

**Issue by houser42** [ch3rn1k/homebridge-multipurpose-kettle#5]
Hello,
Hope you don't mind me asking, but is this plugin close to working with other Xiaomi appliances?
I am trying to find a plugin that works to control the MIJIA INDUCTION COOKER via Homebridge.
Any chance this may work with that also? Is it possible with other plugins without a bridge direct via wifi? Very curious!
Many thanks!
J

**Comment by ch3rn1k** [comment]
Hello man!

This plugin only compactable with Xiaomi Multipurpose Kettle, no way to use it with other devices. On the other hand I see that **MIJIA INDUCTION COOKER** uses Wi-Fi to connect in Mi Home App and that's point to try create a plugin by your hands.

![изображение](https://user-images.githubusercontent.com/19375789/81375533-66494600-910a-11ea-885e-34a87b4f0dc4.png)
